name = "GNSSReceiver"
uuid = "c84cffac-6943-4fe6-9449-f6d23817af8b"
authors = ["Soeren Schoenbrod <soeren.schoenbrod@outlook.de> and contributors"]
version = "0.1.0"

[deps]
Acquisition = "d4bbf60b-102b-5ffb-8f97-a7ea5817e69f"
GNSSDecoder = "bf6b1ec8-12ad-4501-972c-3dec0d675c2b"
GNSSSignals = "52c80523-2a4e-5c38-8979-05588f836870"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PositionVelocityTime = "52ec0b5e-ee36-11ea-211c-3d844fc5682d"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
SoapyLMS7_jll = "e7ed14a0-13eb-5dc7-93e2-6133b2eb8bed"
SoapySDR = "4fa426e6-03fd-45b2-b2dd-25f726820c03"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
Tracking = "10b2438b-ffd4-5096-aa58-44041d5c8f3b"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Acquisition = "0.0.4"
GNSSDecoder = "0.0.1"
GNSSSignals = "0.16"
JLD2 = "0.4"
PositionVelocityTime = "0.0.1"
SoapySDR = "0.3.3, 0.4"
StaticArrays = "1"
Term = "1"
Tracking = "0.14"
UnicodePlots = "3.0.4"
Unitful = "1"
julia = "1.6"

[extras]
AstroTime = "c61b5328-d09d-5e37-a9a8-0eb41c39009c"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Geodesy", "AstroTime", "Random"]
