[deps]
Acquisition = "d4bbf60b-102b-5ffb-8f97-a7ea5817e69f"
AstroTime = "c61b5328-d09d-5e37-a9a8-0eb41c39009c"
GNSSDecoder = "bf6b1ec8-12ad-4501-972c-3dec0d675c2b"
GNSSSignals = "52c80523-2a4e-5c38-8979-05588f836870"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PositionVelocityTime = "52ec0b5e-ee36-11ea-211c-3d844fc5682d"
SoapySDR = "4fa426e6-03fd-45b2-b2dd-25f726820c03"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
Tracking = "10b2438b-ffd4-5096-aa58-44041d5c8f3b"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
